def compare_sequences(seq1, seq2):
    """Compare two sequences and return the percentage of identity between both"""
    if len(seq1) != len(seq2):
        raise ValueError("Sequences must be of the same length")

    matches = sum(1 for a, b in zip(seq1, seq2) if a == b)

    percentage_similarity = (matches / len(seq1)) * 100

    return percentage_similarity


seq1 = "MVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKYRMVHLTPEEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPKVKAHGKKVLGAFSDGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVAGVANALAHKYH"
seq2 = "MVLSAEDKTNVKTFWGKLGAHTAEYGGEALERMFLSFPTTKTYFPHFDMKHDSDQIKAHGKKVADALTRAVGHLDDLPGTLSELSDLHAHKLRVDPINFKLLSHCLLVTLSGHLPEDFTPPVHASLDKFLSNVSTVLTSKYRMVHLTADEKALVTGLWSKVNVKEYGGEALGRLLVVYPWTQRFFEHFGDLSSASAVMHNSKVQTHGEKVLASFGDGLKHLDNLNSAFAELSELHCDKLHVDPENFRLLGNVLVCVLARHLGKEFSPQAQAAYQKVVAGVANALAHKYH"
seq3 = "-VLSAADKTNVKAAWSKVGGNAGEFGAEALERMFLGFPTTKTYFPHFDLSHGSAQVKAHGKKVGDALTLAVGHLDDLPGALSNLSDLHAHKLRVDPVNFKLLSHCLLSTLAVHLPNDFTPAVHASLDKFLSSVSTVLTSKYRMVQLSGEEKTAVLALWGKVNEEEIGGEALGRLLIVYPWTQRFFDSFGHLTTSAAVTGNPRGKAHGKKVLHSFGEGVHHLDNLEDTFAQLSELHCDKLHLDPENFILLGNMLDVVLAHHFGKEFIPELQASYQKALSGGAHALAHKYH"

print(compare_sequences(seq1, seq3))
